services:
  ollama:
    build:
      context: .
      dockerfile: ollama.dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    container_name: ollama\


  postgres:
    build:
      context: .
      dockerfile: postgre.dockerfile
    image: postgres-ai:v1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

networks:
  default:
    driver: bridge